<?php
/**
 * StockLinesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace iPosExchanger\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
#region SPY Code
use GuzzleHttp\Cookie\CookieJar;
#endregion
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use iPosExchanger\ApiException;
use iPosExchanger\Configuration;
use iPosExchanger\HeaderSelector;
use iPosExchanger\ObjectSerializer;

/**
 * StockLinesApi Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StockLinesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

	#region SPY Code
	protected $bXDebugOnInstance	= false;
	protected $bXDebugOnNextRequest;

	/**
	 * @param bool $bXDebugOnInstance
	 * @return $this
	 */
	public function setXDebugOnInstance(bool $bXDebugOnInstance)
	{
		$this->bXDebugOnInstance	= $bXDebugOnInstance;

		return $this;
	}

	/**
	 * @return $this
	 */
	public function setXDebugOnNextRequest()
	{
		$this->bXDebugOnNextRequest	= true;

		return $this;
	}

	/**
	 * Gets the OpenAPI Spec Version
	 *
	 * @return string
	 */
	public static function getSpecVersion()
	{
		return '1.0.0';
	}
	#endregion

    /**
    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createStockLine' => [
            'application/json',
        ],
        'findStockLines' => [
            'application/json',
        ],
        'getStockLines' => [
            'application/json',
        ],
        'updateStockLine' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createStockLine
     *
     * Creates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStockLine'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject
     */
    public function createStockLine($str_database, $data = null, string $contentType = self::contentTypes['createStockLine'][0])
    {
        list($response) = $this->createStockLineWithHttpInfo($str_database, $data, $contentType);
        return $response;
    }

    /**
     * Operation createStockLineWithHttpInfo
     *
     * Creates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStockLine'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function createStockLineWithHttpInfo($str_database, $data = null, string $contentType = self::contentTypes['createStockLine'][0])
    {
        $request = $this->createStockLineRequest($str_database, $data, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\iPosExchanger\Model\DefaultResponseObject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createStockLineAsync
     *
     * Creates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStockLine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStockLineAsync($str_database, $data = null, string $contentType = self::contentTypes['createStockLine'][0])
    {
        return $this->createStockLineAsyncWithHttpInfo($str_database, $data, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createStockLineAsyncWithHttpInfo
     *
     * Creates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStockLine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStockLineAsyncWithHttpInfo($str_database, $data = null, string $contentType = self::contentTypes['createStockLine'][0])
    {
        $returnType = '\iPosExchanger\Model\DefaultResponseObject';
        $request = $this->createStockLineRequest($str_database, $data, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createStockLine'
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStockLine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createStockLineRequest($str_database, $data = null, string $contentType = self::contentTypes['createStockLine'][0])
    {

        // verify the required parameter 'str_database' is set
        if ($str_database === null || (is_array($str_database) && count($str_database) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $str_database when calling createStockLine'
            );
        }



        $resourcePath = '/{strDatabase}/layouts/api_lager/records';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($str_database !== null) {
            $resourcePath = str_replace(
                '{' . 'strDatabase' . '}',
                ObjectSerializer::toPathValue($str_database),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($data)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($data));
            } else {
                $httpBody = $data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findStockLines
     *
     * finds stock lines
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  string $x_spy_use_next_middleware use Next Middleware to paginate (optional, default to '1')
     * @param  \iPosExchanger\Model\FindStockItemsRequest $data Search data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findStockLines'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iPosExchanger\Model\FindStockItemsResponse|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject
     */
    public function findStockLines($str_database, $x_spy_use_next_middleware = '1', $data = null, string $contentType = self::contentTypes['findStockLines'][0])
    {
        list($response) = $this->findStockLinesWithHttpInfo($str_database, $x_spy_use_next_middleware, $data, $contentType);
        return $response;
    }

    /**
     * Operation findStockLinesWithHttpInfo
     *
     * finds stock lines
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  string $x_spy_use_next_middleware use Next Middleware to paginate (optional, default to '1')
     * @param  \iPosExchanger\Model\FindStockItemsRequest $data Search data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findStockLines'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iPosExchanger\Model\FindStockItemsResponse|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function findStockLinesWithHttpInfo($str_database, $x_spy_use_next_middleware = '1', $data = null, string $contentType = self::contentTypes['findStockLines'][0])
    {
        $request = $this->findStockLinesRequest($str_database, $x_spy_use_next_middleware, $data, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\iPosExchanger\Model\FindStockItemsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\FindStockItemsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\FindStockItemsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\iPosExchanger\Model\FindStockItemsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\FindStockItemsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findStockLinesAsync
     *
     * finds stock lines
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  string $x_spy_use_next_middleware use Next Middleware to paginate (optional, default to '1')
     * @param  \iPosExchanger\Model\FindStockItemsRequest $data Search data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findStockLines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findStockLinesAsync($str_database, $x_spy_use_next_middleware = '1', $data = null, string $contentType = self::contentTypes['findStockLines'][0])
    {
        return $this->findStockLinesAsyncWithHttpInfo($str_database, $x_spy_use_next_middleware, $data, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findStockLinesAsyncWithHttpInfo
     *
     * finds stock lines
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  string $x_spy_use_next_middleware use Next Middleware to paginate (optional, default to '1')
     * @param  \iPosExchanger\Model\FindStockItemsRequest $data Search data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findStockLines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findStockLinesAsyncWithHttpInfo($str_database, $x_spy_use_next_middleware = '1', $data = null, string $contentType = self::contentTypes['findStockLines'][0])
    {
        $returnType = '\iPosExchanger\Model\FindStockItemsResponse';
        $request = $this->findStockLinesRequest($str_database, $x_spy_use_next_middleware, $data, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findStockLines'
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  string $x_spy_use_next_middleware use Next Middleware to paginate (optional, default to '1')
     * @param  \iPosExchanger\Model\FindStockItemsRequest $data Search data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findStockLines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findStockLinesRequest($str_database, $x_spy_use_next_middleware = '1', $data = null, string $contentType = self::contentTypes['findStockLines'][0])
    {

        // verify the required parameter 'str_database' is set
        if ($str_database === null || (is_array($str_database) && count($str_database) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $str_database when calling findStockLines'
            );
        }




        $resourcePath = '/{strDatabase}/layouts/api_lager/_find';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_spy_use_next_middleware !== null) {
            $headerParams['X-Spy-UseNextMiddleware'] = ObjectSerializer::toHeaderValue($x_spy_use_next_middleware);
        }

        // path params
        if ($str_database !== null) {
            $resourcePath = str_replace(
                '{' . 'strDatabase' . '}',
                ObjectSerializer::toPathValue($str_database),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($data)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($data));
            } else {
                $httpBody = $data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStockLines
     *
     * retrieves a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStockLines'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iPosExchanger\Model\FindStockItemsResponse|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject
     */
    public function getStockLines($str_database, $i_record_id, string $contentType = self::contentTypes['getStockLines'][0])
    {
        list($response) = $this->getStockLinesWithHttpInfo($str_database, $i_record_id, $contentType);
        return $response;
    }

    /**
     * Operation getStockLinesWithHttpInfo
     *
     * retrieves a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStockLines'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iPosExchanger\Model\FindStockItemsResponse|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStockLinesWithHttpInfo($str_database, $i_record_id, string $contentType = self::contentTypes['getStockLines'][0])
    {
        $request = $this->getStockLinesRequest($str_database, $i_record_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\iPosExchanger\Model\FindStockItemsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\FindStockItemsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\FindStockItemsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\iPosExchanger\Model\FindStockItemsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\FindStockItemsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getStockLinesAsync
     *
     * retrieves a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStockLines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStockLinesAsync($str_database, $i_record_id, string $contentType = self::contentTypes['getStockLines'][0])
    {
        return $this->getStockLinesAsyncWithHttpInfo($str_database, $i_record_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStockLinesAsyncWithHttpInfo
     *
     * retrieves a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStockLines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStockLinesAsyncWithHttpInfo($str_database, $i_record_id, string $contentType = self::contentTypes['getStockLines'][0])
    {
        $returnType = '\iPosExchanger\Model\FindStockItemsResponse';
        $request = $this->getStockLinesRequest($str_database, $i_record_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStockLines'
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStockLines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStockLinesRequest($str_database, $i_record_id, string $contentType = self::contentTypes['getStockLines'][0])
    {

        // verify the required parameter 'str_database' is set
        if ($str_database === null || (is_array($str_database) && count($str_database) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $str_database when calling getStockLines'
            );
        }

        // verify the required parameter 'i_record_id' is set
        if ($i_record_id === null || (is_array($i_record_id) && count($i_record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $i_record_id when calling getStockLines'
            );
        }


        $resourcePath = '/{strDatabase}/layouts/api_lager/records/{iRecordID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($str_database !== null) {
            $resourcePath = str_replace(
                '{' . 'strDatabase' . '}',
                ObjectSerializer::toPathValue($str_database),
                $resourcePath
            );
        }
        // path params
        if ($i_record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'iRecordID' . '}',
                ObjectSerializer::toPathValue($i_record_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateStockLine
     *
     * Updates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStockLine'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject
     */
    public function updateStockLine($str_database, $i_record_id, $data = null, string $contentType = self::contentTypes['updateStockLine'][0])
    {
        list($response) = $this->updateStockLineWithHttpInfo($str_database, $i_record_id, $data, $contentType);
        return $response;
    }

    /**
     * Operation updateStockLineWithHttpInfo
     *
     * Updates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStockLine'] to see the possible values for this operation
     *
     * @throws \iPosExchanger\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject|\iPosExchanger\Model\DefaultResponseObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateStockLineWithHttpInfo($str_database, $i_record_id, $data = null, string $contentType = self::contentTypes['updateStockLine'][0])
    {
        $request = $this->updateStockLineRequest($str_database, $i_record_id, $data, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\iPosExchanger\Model\DefaultResponseObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\iPosExchanger\Model\DefaultResponseObject' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\iPosExchanger\Model\DefaultResponseObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\iPosExchanger\Model\DefaultResponseObject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iPosExchanger\Model\DefaultResponseObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateStockLineAsync
     *
     * Updates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStockLine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateStockLineAsync($str_database, $i_record_id, $data = null, string $contentType = self::contentTypes['updateStockLine'][0])
    {
        return $this->updateStockLineAsyncWithHttpInfo($str_database, $i_record_id, $data, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateStockLineAsyncWithHttpInfo
     *
     * Updates a Stock line entry
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStockLine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateStockLineAsyncWithHttpInfo($str_database, $i_record_id, $data = null, string $contentType = self::contentTypes['updateStockLine'][0])
    {
        $returnType = '\iPosExchanger\Model\DefaultResponseObject';
        $request = $this->updateStockLineRequest($str_database, $i_record_id, $data, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateStockLine'
     *
     * @param  string $str_database Target Database in FileMaker (required)
     * @param  int $i_record_id FileMaker record id (required)
     * @param  \iPosExchanger\Model\CreateOrUpdateStockItemRequest $data (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStockLine'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateStockLineRequest($str_database, $i_record_id, $data = null, string $contentType = self::contentTypes['updateStockLine'][0])
    {

        // verify the required parameter 'str_database' is set
        if ($str_database === null || (is_array($str_database) && count($str_database) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $str_database when calling updateStockLine'
            );
        }

        // verify the required parameter 'i_record_id' is set
        if ($i_record_id === null || (is_array($i_record_id) && count($i_record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $i_record_id when calling updateStockLine'
            );
        }



        $resourcePath = '/{strDatabase}/layouts/api_lager/records/{iRecordID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($str_database !== null) {
            $resourcePath = str_replace(
                '{' . 'strDatabase' . '}',
                ObjectSerializer::toPathValue($str_database),
                $resourcePath
            );
        }
        // path params
        if ($i_record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'iRecordID' . '}',
                ObjectSerializer::toPathValue($i_record_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($data)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($data));
            } else {
                $httpBody = $data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

		#region SPY Code
		$options[RequestOptions::HEADERS]	= [
			'X-OpenAPISpecVersion'	=> '1.0.0',
		];
		$bEnableXDebug	= $this->bXDebugOnNextRequest;

		if($bEnableXDebug === null)
		{
			$bEnableXDebug	= $this->bXDebugOnInstance;
		}

		$this->bXDebugOnNextRequest	= null;

		if($bEnableXDebug)
		{
			if(preg_match('/^(?:https?:\/\/)?([^\/:]+\.[^\/:]+)/i', $this->getConfig()->getHost(), $arrMatches) === 1)
			{
				$options['cookies'] = CookieJar::fromArray(
					[
						'XDEBUG_SESSION'	=> 'PHPSTORM',
					],
					$arrMatches[1]
				);
			}
		}
		#endregion

        return $options;
    }
}
