<?php
/**
 * DeliveryLine
 *
 * PHP version 5
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace iPosExchanger\Model;

use \ArrayAccess;
use \iPosExchanger\ObjectSerializer;

/**
 * DeliveryLine Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeliveryLine implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeliveryLine';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id_varemodtagelse' => 'string',
        'id_vare' => 'string',
        'antal_modtaget' => 'string',
        'ean' => 'string',
        'kospris_nu' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'id_varemodtagelse' => null,
        'id_vare' => null,
        'antal_modtaget' => null,
        'ean' => null,
        'kospris_nu' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_varemodtagelse' => 'id_varemodtagelse',
        'id_vare' => 'id_vare',
        'antal_modtaget' => 'Antal_modtaget',
        'ean' => 'EAN',
        'kospris_nu' => 'Kospris_nu'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_varemodtagelse' => 'setIdVaremodtagelse',
        'id_vare' => 'setIdVare',
        'antal_modtaget' => 'setAntalModtaget',
        'ean' => 'setEan',
        'kospris_nu' => 'setKosprisNu'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_varemodtagelse' => 'getIdVaremodtagelse',
        'id_vare' => 'getIdVare',
        'antal_modtaget' => 'getAntalModtaget',
        'ean' => 'getEan',
        'kospris_nu' => 'getKosprisNu'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_varemodtagelse'] = isset($data['id_varemodtagelse']) ? $data['id_varemodtagelse'] : null;
        $this->container['id_vare'] = isset($data['id_vare']) ? $data['id_vare'] : null;
        $this->container['antal_modtaget'] = isset($data['antal_modtaget']) ? $data['antal_modtaget'] : null;
        $this->container['ean'] = isset($data['ean']) ? $data['ean'] : null;
        $this->container['kospris_nu'] = isset($data['kospris_nu']) ? $data['kospris_nu'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_varemodtagelse
     *
     * @return string|null
     */
    public function getIdVaremodtagelse()
    {
        return $this->container['id_varemodtagelse'];
    }

    /**
     * Sets id_varemodtagelse
     *
     * @param string|null $id_varemodtagelse id_varemodtagelse
     *
     * @return $this
     */
    public function setIdVaremodtagelse($id_varemodtagelse)
    {
        $this->container['id_varemodtagelse'] = $id_varemodtagelse;

        return $this;
    }

    /**
     * Gets id_vare
     *
     * @return string|null
     */
    public function getIdVare()
    {
        return $this->container['id_vare'];
    }

    /**
     * Sets id_vare
     *
     * @param string|null $id_vare id_vare
     *
     * @return $this
     */
    public function setIdVare($id_vare)
    {
        $this->container['id_vare'] = $id_vare;

        return $this;
    }

    /**
     * Gets antal_modtaget
     *
     * @return string|null
     */
    public function getAntalModtaget()
    {
        return $this->container['antal_modtaget'];
    }

    /**
     * Sets antal_modtaget
     *
     * @param string|null $antal_modtaget antal_modtaget
     *
     * @return $this
     */
    public function setAntalModtaget($antal_modtaget)
    {
        $this->container['antal_modtaget'] = $antal_modtaget;

        return $this;
    }

    /**
     * Gets ean
     *
     * @return string|null
     */
    public function getEan()
    {
        return $this->container['ean'];
    }

    /**
     * Sets ean
     *
     * @param string|null $ean ean
     *
     * @return $this
     */
    public function setEan($ean)
    {
        $this->container['ean'] = $ean;

        return $this;
    }

    /**
     * Gets kospris_nu
     *
     * @return string|null
     */
    public function getKosprisNu()
    {
        return $this->container['kospris_nu'];
    }

    /**
     * Sets kospris_nu
     *
     * @param string|null $kospris_nu kospris_nu
     *
     * @return $this
     */
    public function setKosprisNu($kospris_nu)
    {
        $this->container['kospris_nu'] = $kospris_nu;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


