<?php
/**
 * Payment
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace iPosExchanger\Model;

use \ArrayAccess;
use \iPosExchanger\ObjectSerializer;

/**
 * Payment Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Payment implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return PaymentModelFields
      */
    public static function GetModelFields(): PaymentModelFields
    {
        return new PaymentModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return PaymentModelAttributes
      */
    public static function GetModelAttributes(): PaymentModelAttributes
    {
        return new PaymentModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Payment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'dato' => 'string',
        'tekst' => 'string',
        'kto_debet' => 'string',
        'kto_kredit' => 'string',
        'belb' => 'float',
        'spy_relevant' => 'string',
        'spy_done' => 'string',
        'id_lokation' => 'string',
        'spy_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'dato' => null,
        'tekst' => null,
        'kto_debet' => null,
        'kto_kredit' => null,
        'belb' => null,
        'spy_relevant' => null,
        'spy_done' => null,
        'id_lokation' => null,
        'spy_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'dato' => false,
		'tekst' => false,
		'kto_debet' => false,
		'kto_kredit' => false,
		'belb' => false,
		'spy_relevant' => false,
		'spy_done' => false,
		'id_lokation' => false,
		'spy_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dato' => 'dato',
        'tekst' => 'tekst',
        'kto_debet' => 'kto_debet',
        'kto_kredit' => 'kto_kredit',
        'belb' => 'Beløb',
        'spy_relevant' => 'SPY_relevant',
        'spy_done' => 'SPY_done',
        'id_lokation' => 'id_lokation',
        'spy_type' => 'spy_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dato' => 'setDato',
        'tekst' => 'setTekst',
        'kto_debet' => 'setKtoDebet',
        'kto_kredit' => 'setKtoKredit',
        'belb' => 'setBelb',
        'spy_relevant' => 'setSpyRelevant',
        'spy_done' => 'setSpyDone',
        'id_lokation' => 'setIdLokation',
        'spy_type' => 'setSpyType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dato' => 'getDato',
        'tekst' => 'getTekst',
        'kto_debet' => 'getKtoDebet',
        'kto_kredit' => 'getKtoKredit',
        'belb' => 'getBelb',
        'spy_relevant' => 'getSpyRelevant',
        'spy_done' => 'getSpyDone',
        'id_lokation' => 'getIdLokation',
        'spy_type' => 'getSpyType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('dato', $data ?? [], null);
        $this->setIfExists('tekst', $data ?? [], null);
        $this->setIfExists('kto_debet', $data ?? [], null);
        $this->setIfExists('kto_kredit', $data ?? [], null);
        $this->setIfExists('belb', $data ?? [], null);
        $this->setIfExists('spy_relevant', $data ?? [], null);
        $this->setIfExists('spy_done', $data ?? [], null);
        $this->setIfExists('id_lokation', $data ?? [], null);
        $this->setIfExists('spy_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dato
     *
     * @return string|null
     */
    public function getDato()
    {
        return $this->container['dato'];
    }

    /**
     * Sets dato
     *
     * @param string|null $dato dato
     *
     * @return self
     */
    public function setDato($dato)
    {
        if (is_null($dato)) {
            throw new \InvalidArgumentException('non-nullable dato cannot be null');
        }
        $this->container['dato'] = $dato;

        return $this;
    }

    /**
     * Gets tekst
     *
     * @return string|null
     */
    public function getTekst()
    {
        return $this->container['tekst'];
    }

    /**
     * Sets tekst
     *
     * @param string|null $tekst tekst
     *
     * @return self
     */
    public function setTekst($tekst)
    {
        if (is_null($tekst)) {
            throw new \InvalidArgumentException('non-nullable tekst cannot be null');
        }
        $this->container['tekst'] = $tekst;

        return $this;
    }

    /**
     * Gets kto_debet
     *
     * @return string|null
     */
    public function getKtoDebet()
    {
        return $this->container['kto_debet'];
    }

    /**
     * Sets kto_debet
     *
     * @param string|null $kto_debet kto_debet
     *
     * @return self
     */
    public function setKtoDebet($kto_debet)
    {
        if (is_null($kto_debet)) {
            throw new \InvalidArgumentException('non-nullable kto_debet cannot be null');
        }
        $this->container['kto_debet'] = $kto_debet;

        return $this;
    }

    /**
     * Gets kto_kredit
     *
     * @return string|null
     */
    public function getKtoKredit()
    {
        return $this->container['kto_kredit'];
    }

    /**
     * Sets kto_kredit
     *
     * @param string|null $kto_kredit kto_kredit
     *
     * @return self
     */
    public function setKtoKredit($kto_kredit)
    {
        if (is_null($kto_kredit)) {
            throw new \InvalidArgumentException('non-nullable kto_kredit cannot be null');
        }
        $this->container['kto_kredit'] = $kto_kredit;

        return $this;
    }

    /**
     * Gets belb
     *
     * @return float|null
     */
    public function getBelb()
    {
        return $this->container['belb'];
    }

    /**
     * Sets belb
     *
     * @param float|null $belb belb
     *
     * @return self
     */
    public function setBelb($belb)
    {
        if (is_null($belb)) {
            throw new \InvalidArgumentException('non-nullable belb cannot be null');
        }
        $this->container['belb'] = $belb;

        return $this;
    }

    /**
     * Gets spy_relevant
     *
     * @return string|null
     */
    public function getSpyRelevant()
    {
        return $this->container['spy_relevant'];
    }

    /**
     * Sets spy_relevant
     *
     * @param string|null $spy_relevant spy_relevant
     *
     * @return self
     */
    public function setSpyRelevant($spy_relevant)
    {
        if (is_null($spy_relevant)) {
            throw new \InvalidArgumentException('non-nullable spy_relevant cannot be null');
        }
        $this->container['spy_relevant'] = $spy_relevant;

        return $this;
    }

    /**
     * Gets spy_done
     *
     * @return string|null
     */
    public function getSpyDone()
    {
        return $this->container['spy_done'];
    }

    /**
     * Sets spy_done
     *
     * @param string|null $spy_done spy_done
     *
     * @return self
     */
    public function setSpyDone($spy_done)
    {
        if (is_null($spy_done)) {
            throw new \InvalidArgumentException('non-nullable spy_done cannot be null');
        }
        $this->container['spy_done'] = $spy_done;

        return $this;
    }

    /**
     * Gets id_lokation
     *
     * @return string|null
     */
    public function getIdLokation()
    {
        return $this->container['id_lokation'];
    }

    /**
     * Sets id_lokation
     *
     * @param string|null $id_lokation id_lokation
     *
     * @return self
     */
    public function setIdLokation($id_lokation)
    {
        if (is_null($id_lokation)) {
            throw new \InvalidArgumentException('non-nullable id_lokation cannot be null');
        }
        $this->container['id_lokation'] = $id_lokation;

        return $this;
    }

    /**
     * Gets spy_type
     *
     * @return string|null
     */
    public function getSpyType()
    {
        return $this->container['spy_type'];
    }

    /**
     * Sets spy_type
     *
     * @param string|null $spy_type spy_type
     *
     * @return self
     */
    public function setSpyType($spy_type)
    {
        if (is_null($spy_type)) {
            throw new \InvalidArgumentException('non-nullable spy_type cannot be null');
        }
        $this->container['spy_type'] = $spy_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


