<?php
/**
 * ProductModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace iPosExchanger\Model;

/**
 * ProductModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductModelAttributes
{
    public string $strId = 'id';
    public string $strEanNr = 'ean_nr';
    public string $strVaretekst = 'varetekst';
    public string $strVareBeskrivelse = 'vare_beskrivelse';
    public string $strVarenrLeverandr = 'varenr_leverandr';
    public string $strSalgspris = 'salgspris';
    public string $strSalgsprisInclMoms = 'salgspris_incl_moms';
    public string $strKostpris = 'kostpris';
    public string $strKostprisDkk = 'kostpris_dkk';
    public string $strAvanceIKr = 'avance_i_kr';
    public string $strIdVaregruppe = 'id_varegruppe';
    public string $strLagerStatusNskes = 'lager_status_nskes';
    public string $strColor = 'color';
    public string $strSize = 'size';
    public string $strMomsSats = 'moms_sats';
    public string $strSaeson = 'saeson';
    public string $strProducentNavn = 'producent_navn';
}

