<?php
/**
 * SalesReportModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace iPosExchanger\Model;

/**
 * SalesReportModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesReportModelAttributes
{
    public string $strAntal = 'antal';
    public string $strEan = 'ean';
    public string $strSpyAPris = 'spy_a_pris';
    public string $strUiDatoBon = 'ui_dato_bon';
    public string $strLgIkkePLager = 'lg_ikke_p_lager';
    public string $strSpyRelevant = 'spy_relevant';
    public string $strSpyDone = 'spy_done';
    public string $strIdLokation = 'id_lokation';
    public string $strTaxStateAmount = 'tax_state_amount';
    public string $strTaxCityAmount = 'tax_city_amount';
    public string $strTaxStateRate = 'tax_state_rate';
    public string $strTaxCityRate = 'tax_city_rate';
    public string $strSpyId = 'spy_id';
}

