<?php
/**
 * SalesReport
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace iPosExchanger\Model;

use \ArrayAccess;
use \iPosExchanger\ObjectSerializer;

/**
 * SalesReport Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SalesReport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return SalesReportModelFields
      */
    public static function GetModelFields(): SalesReportModelFields
    {
        return new SalesReportModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return SalesReportModelAttributes
      */
    public static function GetModelAttributes(): SalesReportModelAttributes
    {
        return new SalesReportModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SalesReport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'antal' => 'string',
        'ean' => 'string',
        'spy_a_pris' => 'string',
        'ui_dato_bon' => 'string',
        'lg_ikke_p_lager' => 'string',
        'spy_relevant' => 'string',
        'spy_done' => 'string',
        'id_lokation' => 'string',
        'tax_state_amount' => 'string',
        'tax_city_amount' => 'string',
        'tax_state_rate' => 'string',
        'tax_city_rate' => 'string',
        'spy_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'antal' => null,
        'ean' => null,
        'spy_a_pris' => null,
        'ui_dato_bon' => null,
        'lg_ikke_p_lager' => null,
        'spy_relevant' => null,
        'spy_done' => null,
        'id_lokation' => null,
        'tax_state_amount' => null,
        'tax_city_amount' => null,
        'tax_state_rate' => null,
        'tax_city_rate' => null,
        'spy_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'antal' => false,
		'ean' => false,
		'spy_a_pris' => false,
		'ui_dato_bon' => false,
		'lg_ikke_p_lager' => false,
		'spy_relevant' => false,
		'spy_done' => false,
		'id_lokation' => false,
		'tax_state_amount' => false,
		'tax_city_amount' => false,
		'tax_state_rate' => false,
		'tax_city_rate' => false,
		'spy_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'antal' => 'Antal',
        'ean' => 'ean',
        'spy_a_pris' => 'SPY_a_pris',
        'ui_dato_bon' => 'UI_dato_bon',
        'lg_ikke_p_lager' => 'Læg_ikke_på_lager',
        'spy_relevant' => 'SPY_relevant',
        'spy_done' => 'SPY_done',
        'id_lokation' => 'id_lokation',
        'tax_state_amount' => 'tax_state_amount',
        'tax_city_amount' => 'tax_city_amount',
        'tax_state_rate' => 'tax_state_rate',
        'tax_city_rate' => 'tax_city_rate',
        'spy_id' => 'SPY_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'antal' => 'setAntal',
        'ean' => 'setEan',
        'spy_a_pris' => 'setSpyAPris',
        'ui_dato_bon' => 'setUiDatoBon',
        'lg_ikke_p_lager' => 'setLgIkkePLager',
        'spy_relevant' => 'setSpyRelevant',
        'spy_done' => 'setSpyDone',
        'id_lokation' => 'setIdLokation',
        'tax_state_amount' => 'setTaxStateAmount',
        'tax_city_amount' => 'setTaxCityAmount',
        'tax_state_rate' => 'setTaxStateRate',
        'tax_city_rate' => 'setTaxCityRate',
        'spy_id' => 'setSpyId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'antal' => 'getAntal',
        'ean' => 'getEan',
        'spy_a_pris' => 'getSpyAPris',
        'ui_dato_bon' => 'getUiDatoBon',
        'lg_ikke_p_lager' => 'getLgIkkePLager',
        'spy_relevant' => 'getSpyRelevant',
        'spy_done' => 'getSpyDone',
        'id_lokation' => 'getIdLokation',
        'tax_state_amount' => 'getTaxStateAmount',
        'tax_city_amount' => 'getTaxCityAmount',
        'tax_state_rate' => 'getTaxStateRate',
        'tax_city_rate' => 'getTaxCityRate',
        'spy_id' => 'getSpyId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('antal', $data ?? [], null);
        $this->setIfExists('ean', $data ?? [], null);
        $this->setIfExists('spy_a_pris', $data ?? [], null);
        $this->setIfExists('ui_dato_bon', $data ?? [], null);
        $this->setIfExists('lg_ikke_p_lager', $data ?? [], null);
        $this->setIfExists('spy_relevant', $data ?? [], null);
        $this->setIfExists('spy_done', $data ?? [], null);
        $this->setIfExists('id_lokation', $data ?? [], null);
        $this->setIfExists('tax_state_amount', $data ?? [], null);
        $this->setIfExists('tax_city_amount', $data ?? [], null);
        $this->setIfExists('tax_state_rate', $data ?? [], null);
        $this->setIfExists('tax_city_rate', $data ?? [], null);
        $this->setIfExists('spy_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets antal
     *
     * @return string|null
     */
    public function getAntal()
    {
        return $this->container['antal'];
    }

    /**
     * Sets antal
     *
     * @param string|null $antal antal
     *
     * @return self
     */
    public function setAntal($antal)
    {

        if (is_null($antal)) {
            throw new \InvalidArgumentException('non-nullable antal cannot be null');
        }

        $this->container['antal'] = $antal;

        return $this;
    }

    /**
     * Gets ean
     *
     * @return string|null
     */
    public function getEan()
    {
        return $this->container['ean'];
    }

    /**
     * Sets ean
     *
     * @param string|null $ean ean
     *
     * @return self
     */
    public function setEan($ean)
    {

        if (is_null($ean)) {
            throw new \InvalidArgumentException('non-nullable ean cannot be null');
        }

        $this->container['ean'] = $ean;

        return $this;
    }

    /**
     * Gets spy_a_pris
     *
     * @return string|null
     */
    public function getSpyAPris()
    {
        return $this->container['spy_a_pris'];
    }

    /**
     * Sets spy_a_pris
     *
     * @param string|null $spy_a_pris spy_a_pris
     *
     * @return self
     */
    public function setSpyAPris($spy_a_pris)
    {

        if (is_null($spy_a_pris)) {
            throw new \InvalidArgumentException('non-nullable spy_a_pris cannot be null');
        }

        $this->container['spy_a_pris'] = $spy_a_pris;

        return $this;
    }

    /**
     * Gets ui_dato_bon
     *
     * @return string|null
     */
    public function getUiDatoBon()
    {
        return $this->container['ui_dato_bon'];
    }

    /**
     * Sets ui_dato_bon
     *
     * @param string|null $ui_dato_bon ui_dato_bon
     *
     * @return self
     */
    public function setUiDatoBon($ui_dato_bon)
    {

        if (is_null($ui_dato_bon)) {
            throw new \InvalidArgumentException('non-nullable ui_dato_bon cannot be null');
        }

        $this->container['ui_dato_bon'] = $ui_dato_bon;

        return $this;
    }

    /**
     * Gets lg_ikke_p_lager
     *
     * @return string|null
     */
    public function getLgIkkePLager()
    {
        return $this->container['lg_ikke_p_lager'];
    }

    /**
     * Sets lg_ikke_p_lager
     *
     * @param string|null $lg_ikke_p_lager lg_ikke_p_lager
     *
     * @return self
     */
    public function setLgIkkePLager($lg_ikke_p_lager)
    {

        if (is_null($lg_ikke_p_lager)) {
            throw new \InvalidArgumentException('non-nullable lg_ikke_p_lager cannot be null');
        }

        $this->container['lg_ikke_p_lager'] = $lg_ikke_p_lager;

        return $this;
    }

    /**
     * Gets spy_relevant
     *
     * @return string|null
     */
    public function getSpyRelevant()
    {
        return $this->container['spy_relevant'];
    }

    /**
     * Sets spy_relevant
     *
     * @param string|null $spy_relevant spy_relevant
     *
     * @return self
     */
    public function setSpyRelevant($spy_relevant)
    {

        if (is_null($spy_relevant)) {
            throw new \InvalidArgumentException('non-nullable spy_relevant cannot be null');
        }

        $this->container['spy_relevant'] = $spy_relevant;

        return $this;
    }

    /**
     * Gets spy_done
     *
     * @return string|null
     */
    public function getSpyDone()
    {
        return $this->container['spy_done'];
    }

    /**
     * Sets spy_done
     *
     * @param string|null $spy_done spy_done
     *
     * @return self
     */
    public function setSpyDone($spy_done)
    {

        if (is_null($spy_done)) {
            throw new \InvalidArgumentException('non-nullable spy_done cannot be null');
        }

        $this->container['spy_done'] = $spy_done;

        return $this;
    }

    /**
     * Gets id_lokation
     *
     * @return string|null
     */
    public function getIdLokation()
    {
        return $this->container['id_lokation'];
    }

    /**
     * Sets id_lokation
     *
     * @param string|null $id_lokation id_lokation
     *
     * @return self
     */
    public function setIdLokation($id_lokation)
    {

        if (is_null($id_lokation)) {
            throw new \InvalidArgumentException('non-nullable id_lokation cannot be null');
        }

        $this->container['id_lokation'] = $id_lokation;

        return $this;
    }

    /**
     * Gets tax_state_amount
     *
     * @return string|null
     */
    public function getTaxStateAmount()
    {
        return $this->container['tax_state_amount'];
    }

    /**
     * Sets tax_state_amount
     *
     * @param string|null $tax_state_amount tax_state_amount
     *
     * @return self
     */
    public function setTaxStateAmount($tax_state_amount)
    {

        if (is_null($tax_state_amount)) {
            throw new \InvalidArgumentException('non-nullable tax_state_amount cannot be null');
        }

        $this->container['tax_state_amount'] = $tax_state_amount;

        return $this;
    }

    /**
     * Gets tax_city_amount
     *
     * @return string|null
     */
    public function getTaxCityAmount()
    {
        return $this->container['tax_city_amount'];
    }

    /**
     * Sets tax_city_amount
     *
     * @param string|null $tax_city_amount tax_city_amount
     *
     * @return self
     */
    public function setTaxCityAmount($tax_city_amount)
    {

        if (is_null($tax_city_amount)) {
            throw new \InvalidArgumentException('non-nullable tax_city_amount cannot be null');
        }

        $this->container['tax_city_amount'] = $tax_city_amount;

        return $this;
    }

    /**
     * Gets tax_state_rate
     *
     * @return string|null
     */
    public function getTaxStateRate()
    {
        return $this->container['tax_state_rate'];
    }

    /**
     * Sets tax_state_rate
     *
     * @param string|null $tax_state_rate tax_state_rate
     *
     * @return self
     */
    public function setTaxStateRate($tax_state_rate)
    {

        if (is_null($tax_state_rate)) {
            throw new \InvalidArgumentException('non-nullable tax_state_rate cannot be null');
        }

        $this->container['tax_state_rate'] = $tax_state_rate;

        return $this;
    }

    /**
     * Gets tax_city_rate
     *
     * @return string|null
     */
    public function getTaxCityRate()
    {
        return $this->container['tax_city_rate'];
    }

    /**
     * Sets tax_city_rate
     *
     * @param string|null $tax_city_rate tax_city_rate
     *
     * @return self
     */
    public function setTaxCityRate($tax_city_rate)
    {

        if (is_null($tax_city_rate)) {
            throw new \InvalidArgumentException('non-nullable tax_city_rate cannot be null');
        }

        $this->container['tax_city_rate'] = $tax_city_rate;

        return $this;
    }

    /**
     * Gets spy_id
     *
     * @return string|null
     */
    public function getSpyId()
    {
        return $this->container['spy_id'];
    }

    /**
     * Sets spy_id
     *
     * @param string|null $spy_id spy_id
     *
     * @return self
     */
    public function setSpyId($spy_id)
    {

        if (is_null($spy_id)) {
            throw new \InvalidArgumentException('non-nullable spy_id cannot be null');
        }

        $this->container['spy_id'] = $spy_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


