<?php
/**
 * StockTransaction
 *
 * PHP version 5
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace iPosExchanger\Model;

use \ArrayAccess;
use \iPosExchanger\ObjectSerializer;

/**
 * StockTransaction Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StockTransaction implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StockTransaction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id_vare' => 'string',
        'id_lokation' => 'string',
        'antal_lager' => 'string',
        'flytning' => 'string',
        'spy_api_done' => 'string',
        'time_stamp' => 'string',
        'tekst' => 'string',
        'id_tabel' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'id_vare' => null,
        'id_lokation' => null,
        'antal_lager' => null,
        'flytning' => null,
        'spy_api_done' => null,
        'time_stamp' => null,
        'tekst' => null,
        'id_tabel' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_vare' => 'id_vare',
        'id_lokation' => 'id_lokation',
        'antal_lager' => 'Antal_lager',
        'flytning' => 'flytning',
        'spy_api_done' => 'spy_api_done',
        'time_stamp' => 'TimeStamp',
        'tekst' => 'Tekst',
        'id_tabel' => 'ID_tabel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_vare' => 'setIdVare',
        'id_lokation' => 'setIdLokation',
        'antal_lager' => 'setAntalLager',
        'flytning' => 'setFlytning',
        'spy_api_done' => 'setSpyApiDone',
        'time_stamp' => 'setTimeStamp',
        'tekst' => 'setTekst',
        'id_tabel' => 'setIdTabel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_vare' => 'getIdVare',
        'id_lokation' => 'getIdLokation',
        'antal_lager' => 'getAntalLager',
        'flytning' => 'getFlytning',
        'spy_api_done' => 'getSpyApiDone',
        'time_stamp' => 'getTimeStamp',
        'tekst' => 'getTekst',
        'id_tabel' => 'getIdTabel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_vare'] = isset($data['id_vare']) ? $data['id_vare'] : null;
        $this->container['id_lokation'] = isset($data['id_lokation']) ? $data['id_lokation'] : null;
        $this->container['antal_lager'] = isset($data['antal_lager']) ? $data['antal_lager'] : null;
        $this->container['flytning'] = isset($data['flytning']) ? $data['flytning'] : null;
        $this->container['spy_api_done'] = isset($data['spy_api_done']) ? $data['spy_api_done'] : null;
        $this->container['time_stamp'] = isset($data['time_stamp']) ? $data['time_stamp'] : null;
        $this->container['tekst'] = isset($data['tekst']) ? $data['tekst'] : null;
        $this->container['id_tabel'] = isset($data['id_tabel']) ? $data['id_tabel'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_vare
     *
     * @return string|null
     */
    public function getIdVare()
    {
        return $this->container['id_vare'];
    }

    /**
     * Sets id_vare
     *
     * @param string|null $id_vare id_vare
     *
     * @return $this
     */
    public function setIdVare($id_vare)
    {
        $this->container['id_vare'] = $id_vare;

        return $this;
    }

    /**
     * Gets id_lokation
     *
     * @return string|null
     */
    public function getIdLokation()
    {
        return $this->container['id_lokation'];
    }

    /**
     * Sets id_lokation
     *
     * @param string|null $id_lokation id_lokation
     *
     * @return $this
     */
    public function setIdLokation($id_lokation)
    {
        $this->container['id_lokation'] = $id_lokation;

        return $this;
    }

    /**
     * Gets antal_lager
     *
     * @return string|null
     */
    public function getAntalLager()
    {
        return $this->container['antal_lager'];
    }

    /**
     * Sets antal_lager
     *
     * @param string|null $antal_lager antal_lager
     *
     * @return $this
     */
    public function setAntalLager($antal_lager)
    {
        $this->container['antal_lager'] = $antal_lager;

        return $this;
    }

    /**
     * Gets flytning
     *
     * @return string|null
     */
    public function getFlytning()
    {
        return $this->container['flytning'];
    }

    /**
     * Sets flytning
     *
     * @param string|null $flytning flytning
     *
     * @return $this
     */
    public function setFlytning($flytning)
    {
        $this->container['flytning'] = $flytning;

        return $this;
    }

    /**
     * Gets spy_api_done
     *
     * @return string|null
     */
    public function getSpyApiDone()
    {
        return $this->container['spy_api_done'];
    }

    /**
     * Sets spy_api_done
     *
     * @param string|null $spy_api_done spy_api_done
     *
     * @return $this
     */
    public function setSpyApiDone($spy_api_done)
    {
        $this->container['spy_api_done'] = $spy_api_done;

        return $this;
    }

    /**
     * Gets time_stamp
     *
     * @return string|null
     */
    public function getTimeStamp()
    {
        return $this->container['time_stamp'];
    }

    /**
     * Sets time_stamp
     *
     * @param string|null $time_stamp time_stamp
     *
     * @return $this
     */
    public function setTimeStamp($time_stamp)
    {
        $this->container['time_stamp'] = $time_stamp;

        return $this;
    }

    /**
     * Gets tekst
     *
     * @return string|null
     */
    public function getTekst()
    {
        return $this->container['tekst'];
    }

    /**
     * Sets tekst
     *
     * @param string|null $tekst tekst
     *
     * @return $this
     */
    public function setTekst($tekst)
    {
        $this->container['tekst'] = $tekst;

        return $this;
    }

    /**
     * Gets id_tabel
     *
     * @return int|null
     */
    public function getIdTabel()
    {
        return $this->container['id_tabel'];
    }

    /**
     * Sets id_tabel
     *
     * @param int|null $id_tabel id_tabel
     *
     * @return $this
     */
    public function setIdTabel($id_tabel)
    {
        $this->container['id_tabel'] = $id_tabel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


