<?php
/**
 * DeliveryTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace iPosExchanger\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DeliveryTest Class Doc Comment
 *
 * @category    Class
 * @description Delivery
 * @package     iPosExchanger
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeliveryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Delivery"
     */
    public function testDelivery()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_uuid"
     */
    public function testPropertyIdUuid()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_lokation"
     */
    public function testPropertyIdLokation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dato_opr"
     */
    public function testPropertyDatoOpr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
