<?php
/**
 * PaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace iPosExchanger;

/**
 * PaymentTest Class Doc Comment
 *
 * @category    Class
 * @description Payment
 * @package     iPosExchanger
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Payment"
     */
    public function testPayment()
    {
    }

    /**
     * Test attribute "dato"
     */
    public function testPropertyDato()
    {
    }

    /**
     * Test attribute "tekst"
     */
    public function testPropertyTekst()
    {
    }

    /**
     * Test attribute "kto_debet"
     */
    public function testPropertyKtoDebet()
    {
    }

    /**
     * Test attribute "kto_kredit"
     */
    public function testPropertyKtoKredit()
    {
    }

    /**
     * Test attribute "belb"
     */
    public function testPropertyBelb()
    {
    }

    /**
     * Test attribute "spy_relevant"
     */
    public function testPropertySpyRelevant()
    {
    }

    /**
     * Test attribute "spy_done"
     */
    public function testPropertySpyDone()
    {
    }

    /**
     * Test attribute "id_lokation"
     */
    public function testPropertyIdLokation()
    {
    }

    /**
     * Test attribute "spy_type"
     */
    public function testPropertySpyType()
    {
    }
}
