<?php
/**
 * StockTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace iPosExchanger;

/**
 * StockTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description StockTransaction
 * @package     iPosExchanger
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StockTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StockTransaction"
     */
    public function testStockTransaction()
    {
    }

    /**
     * Test attribute "id_vare"
     */
    public function testPropertyIdVare()
    {
    }

    /**
     * Test attribute "id_lokation"
     */
    public function testPropertyIdLokation()
    {
    }

    /**
     * Test attribute "antal_lager"
     */
    public function testPropertyAntalLager()
    {
    }

    /**
     * Test attribute "flytning"
     */
    public function testPropertyFlytning()
    {
    }

    /**
     * Test attribute "spy_api_done"
     */
    public function testPropertySpyApiDone()
    {
    }

    /**
     * Test attribute "time_stamp"
     */
    public function testPropertyTimeStamp()
    {
    }
}
