<?php
/**
 * ProductTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iPos integration for FileMaker 17 API
 *
 * OpenAPI description for the iPOS integration for FileMaker 17 API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace iPosExchanger;

use \iPosExchanger\Configuration;
use \iPosExchanger\ApiException;
use \iPosExchanger\ObjectSerializer;

/**
 * ProductTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  iPosExchanger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProductType
     *
     * Creates a new product type.
     *
     */
    public function testCreateProductType()
    {
    }

    /**
     * Test case for findProductTypes
     *
     * finds a product type based on its Id.
     *
     */
    public function testFindProductTypes()
    {
    }

    /**
     * Test case for getProductTypes
     *
     * retrieves all product types.
     *
     */
    public function testGetProductTypes()
    {
    }
}
